### ISSUE TITLE
ICsi Roadmap

### ISSUE THREAD

**Issue by iurie5100** [iurie5100/icsi#2]
This issue currently tracks the features that will be added in the first release of ICsi.

- [X] Use Roslyn for the script engine
- [ ] Syntax highlighting
- [ ] REPL-specific commands
- [ ] Command-line arguments and options
